# categories in the output order
categories:
- name: ocp_install
  title: OCP Installation
- name: ocp_config
  title: OCP Configuration
- name: ocp_disconnected
  title: OCP Disconnected
- name: ocp_workloads
  title: OCP Workloads
- name: ocs
  title: OpenShift Container Storage
- name: quay
  title: Red Hat Quay
- name: cicd
  title: CI/CD

# repositories in alphabetic order
repositories:
- url: https://github.com/aglenn360/ocp4_aws_upi_tf
  categories: [ ocp_install ]
- url: https://github.com/alexgdmx/ocp4-vmware-terraform
  categories: [ ocp_install ]
- url: https://github.com/ashcrow/filetranspiler
  categories: [ ocp_install ]
- url: https://github.com/bmangoen/openshift-hybrid-install
  categories: [ ocp_install ]
- url: https://github.com/cadjai/mirror-content-for-disconnected-openshift-install
  categories: [ ocp_disconnected ]
- url: https://github.com/christianh814/openshift-toolbox
  categories: [ ocp_install, ocp_config, ocp_workloads ]
- url: https://github.com/chuckersjp/coreos-iso-maker
  categories: [ ocp_install ]
- url: https://github.com/containercraft/ocp-mini-stack
  categories: [ ocp_install ]
- url: https://github.com/dmoessne/ocs-disk-gather
  categories: [ ocs ]
- url: https://github.com/dudash/openshift-simplified-gcp-install
  categories: [ ocp_install ]
- url: https://github.com/e-minguez/ocp4-upi-bm-pxeless-staticips
  categories: [ ocp_install ]
- url: https://github.com/elajoie/lab.local
  categories: [ ocp_install ]
- url: https://github.com/eformat/openshift-disconnected
  categories: [ ocp_disconnected ]
- url: https://github.com/jcordes73/ocp4labs-ansible
  categories: [ ocp_install ]
- url: https://github.com/Koma-Andrea/openshift4_vmware_infra_provisioner
  categories: [ ocp_install ]
- url: https://github.com/kcalliga/42_deployment
  categories: [ ocp_disconnected ]
- url: https://github.com/maci0/openshift4-ansible
  categories: [ ocp_install ]
- url: https://github.com/marbe/ocp4-vmware-upi-installer
  categories: [ ocp_install ]
- url: https://github.com/mikishapiro/ocp4-cluster-install
  categories: [ ocp_install ]
- url: https://github.com/nccurry/okd-4-libvirt
  categories: [ ocp_install ]
- url: https://github.com/noseka1/ocs-kustomization
  categories: [ ocs ]
- url: https://github.com/noseka1/openshift-auto-upi
  categories: [ ocp_install ]
- url: https://github.com/noseka1/openshift-post-install
  categories: [ ocp_config ]
- url: https://github.com/noseka1/quay-kustomization
  categories: [ quay ]
- url: https://github.com/raffaelespazzoli/ocp4-ansible-libvirt
  categories: [ ocp_install ]
- url: https://github.com/RedHatOfficial/ocp4-helpernode
  categories: [ ocp_install ]
- url: https://github.com/red-hat-storage/ocs-training
  categories: [ ocs ]
- url: https://github.com/redhat-cop/agnosticd
  categories: [ ocp_install ]
- url: https://github.com/redhat-cop/containers-quickstarts
  categories: [ cicd ]
- url: https://github.com/redhat-cop/container-pipelines
  categories: [ cicd ]
- url: https://github.com/redhat-cop/infra-ansible
  categories: [ ocp_install ]
- url: https://github.com/redhat-cop/openshift-toolkit
  categories: [ ocp_config ]
- url: https://github.com/redhat-cop/pipeline-library
  categories: [ cicd ]
- url: https://github.com/redhat-cop/ocp4-vsphere-workshop
  categories: [ ocp_install ]
- url: https://github.com/redhat-cop/ocp4-prereqs-validator
  categories: [ ocp_install ]
- url: https://github.com/redhat-cop/openshift-templates
  categories: [ ocp_config, cicd ]
- url: https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4
  categories: [ ocp_install ]
- url: https://github.com/sa-mw-dach/ocp-on-kvm
  categories: [ ocp_install ]
- url: https://github.com/sa-ne/openshift4-rhv-upi
  categories: [ ocp_install ]
- url: https://github.com/sa-ne/openshift4-vmware-upi
  categories: [ ocp_install ]
- url: https://github.com/siamaksade/openshift-cd-demo
  categories: [ cicd ]
- url: https://github.com/sushilsuresh/ocp4-ansible-roles
  categories: [ ocp_config ]
- url: https://github.com/sushilsuresh/ocp4-disconnected
  categories: [ ocp_disconnected ]
- url: https://github.com/sushilsuresh/ocp4-vsphere
  categories: [ ocp_install ]
- url: https://github.com/tosin2013/nfs-provisioner-role
  categories: [ ocp_config ]
- url: https://github.com/tosin2013/openshift-4-deployment-notes
  categories: [ ocp_install ]
- url: https://github.com/tsailiming/openshift4-disconnected
  categories: [ ocp_disconnected ]
- url: https://github.com/tsailiming/openshift4-vmware-upi
  categories: [ ocp_install ]
- url: https://github.com/vchintal/ocp4-vsphere-upi-automation
  categories: [ ocp_install ]
- url: https://github.com/williamcaban/ocp4-lab
  categories: [ ocp_install ]

#Repository('https://gitlab.consulting.redhat.com/nordics/ocp4-vmware-upi-prep', [Category.OCP_INSTALL])
#Repository('https://gitlab.consulting.redhat.com/jnaess/ocp4-prereqs', [Category.OCP_INSTALL])
