# categories in the output order
categories:
- name: ocp_install
  title: OCP Installation
  desc: Projects that automate or enhance the deployment of OCP.
- name: ocp_config
  title: OCP Configuration
  desc: Projects that automate various OCP configuration tasks. There are collections of code samples that help you get started with OpenShift as well.
- name: ocp_disconnected
  title: OCP Disconnected
  desc: Scripts and automation for configuring OCP in disconnected or network restricted environments.
- name: ocp_workloads
  title: OCP Workloads
  desc: Automation for deploying popular workloads on OpenShift.
- name: ocs
  title: OpenShift Container Storage
  desc: Projects that focus on the OpenShift Container Storage product.
- name: quay
  title: Red Hat Quay
  desc: Projects that focus on the Red Hat Quay product.
- name: cicd
  title: CI/CD
  desc: CI/CD on OpenShift using Jenkins, Tekton, Argo CD, or other technologies. Automation and sample code for creating CI/CD pipelines.
- name: test-cicd2
  title: test 2 CI/CD
  desc: Test 2 CI/CD on OpenShift using Jenkins, Tekton, Argo CD, or other technologies. Automation and sample code for creating CI/CD pipelines.

# repositories in alphabetic order
repositories:
- url: https://github.com/aglenn360/ocp4_aws_upi_tf
  categories: [ ocp_install ]
- url: https://github.com/alexgdmx/ocp4-vmware-terraform
  categories: [ ocp_install ]
- url: https://github.com/ashcrow/filetranspiler
  categories: [ ocp_install ]
- url: https://github.com/bmangoen/openshift-hybrid-install
  categories: [ ocp_install ]
- url: https://github.com/cadjai/mirror-content-for-disconnected-openshift-install
  categories: [ ocp_disconnected ]
- url: https://github.com/christianh814/openshift-toolbox
  categories: [ ocp_install, ocp_config, ocp_workloads ]
- url: https://github.com/chuckersjp/coreos-iso-maker
  categories: [ ocp_install ]
- url:  https://github.com/gnunn-gitops/cluster-config-acm
  categories: [ ocp_config ]
- url: https://github.com/darthlukan/gitops-workshop
  categories: [ cicd ]
- url: https://github.com/dgoodwin/openshift4-gitops
  categories: [ cicd ]
- url: https://github.com/dmoessne/ocs-disk-gather
  categories: [ ocs ]
- url: https://github.com/dudash/openshift-simplified-gcp-install
  categories: [ ocp_install ]
- url: https://github.com/e-minguez/ocp4-upi-bm-pxeless-staticips
  categories: [ ocp_install ]
- url: https://github.com/elajoie/lab.local
  categories: [ ocp_install ]
- url: https://github.com/eformat/openshift-disconnected
  categories: [ ocp_disconnected ]
- url: https://github.com/gnunn-gitops/product-catalog
  categories: [ cicd ]
- url: https://github.com/jcordes73/ocp4labs-ansible
  categories: [ ocp_install ]
- url: https://github.com/lbohnsac/OCP4
  categories: [ ocp_config ]
- url: https://github.com/liveaverage/packer-ocp4-vsphere-upi
  categories: [ ocp_install ]
- url: https://github.com/Koma-Andrea/openshift4_vmware_infra_provisioner
  categories: [ ocp_install ]
- url: https://github.com/kcalliga/42_deployment
  categories: [ ocp_disconnected ]
- url: https://github.com/maci0/openshift4-ansible
  categories: [ ocp_install ]
- url: https://github.com/marbe/ocp4-vmware-upi-installer
  categories: [ ocp_install ]
- url: https://github.com/mikishapiro/ocp4-cluster-install
  categories: [ ocp_install ]
- url: https://github.com/mvazquezc/code-to-prod-blog
  categories: [ cicd ]
- url: https://github.com/nccurry/okd-4-libvirt
  categories: [ ocp_install ]
- url: https://github.com/noseka1/ocs-kustomization
  categories: [ ocs ]
- url: https://github.com/noseka1/openshift-auto-upi
  categories: [ ocp_install ]
- url: https://github.com/noseka1/openshift-post-install
  categories: [ ocp_config ]
- url: https://github.com/noseka1/quay-kustomization
  categories: [ quay ]
- url: https://github.com/raffaelespazzoli/ocp4-ansible-libvirt
  categories: [ ocp_install ]
- url: https://github.com/ralvares/ipxe
  categories: [ ocp_install ]
- url: https://github.com/RedHatOfficial/ocp4-helpernode
  categories: [ ocp_install ]
- url: https://github.com/red-hat-storage/ocs-training
  categories: [ ocs ]
- url: https://github.com/redhat-cop/agnosticd
  categories: [ ocp_install ]
- url: https://github.com/redhat-cop/containers-quickstarts
  categories: [ cicd ]
- url: https://github.com/redhat-cop/container-pipelines
  categories: [ cicd ]
- url: https://github.com/redhat-cop/infra-ansible
  categories: [ ocp_install ]
- url: https://github.com/redhat-cop/openshift-toolkit
  categories: [ ocp_config ]
- url: https://github.com/redhat-cop/pipeline-library
  categories: [ cicd ]
- url: https://github.com/redhat-cop/ocp4-vsphere-workshop
  categories: [ ocp_install ]
- url: https://github.com/redhat-cop/ocp4-prereqs-validator
  categories: [ ocp_install ]
- url: https://github.com/redhat-cop/openshift-templates
  categories: [ ocp_config, cicd ]
- url: https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4
  categories: [ ocp_install ]
- url: https://github.com/sa-mw-dach/ocp-on-kvm
  categories: [ ocp_install ]
- url: https://github.com/sa-ne/openshift4-rhv-upi
  categories: [ ocp_install ]
- url: https://github.com/sa-ne/openshift4-vmware-upi
  categories: [ ocp_install ]
- url: https://github.com/sabre1041/group-sync-operator
  categories: [ ocp_config ]
- url: https://github.com/sabre1041/openshift-logforwarding-splunk
  categories: [ ocp_config ]
- url: https://github.com/siamaksade/openshift-cd-demo
  categories: [ cicd ]
- url: https://github.com/spagno/ocp4-utils
  categories: [ ocp_install ]
- url: https://github.com/sushilsuresh/ocp4-all-in-one
  categories: [ ocp_install ]
- url: https://github.com/sushilsuresh/ocp4-ansible-roles
  categories: [ ocp_config ]
- url: https://github.com/sushilsuresh/ocp4-disconnected
  categories: [ ocp_disconnected ]
- url: https://github.com/sushilsuresh/ocp4-vsphere
  categories: [ ocp_install ]
- url: https://github.com/tosin2013/nfs-provisioner-role
  categories: [ ocp_config ]
- url: https://github.com/tosin2013/openshift-4-deployment-notes
  categories: [ ocp_install ]
- url: https://github.com/tsailiming/openshift4-disconnected
  categories: [ ocp_disconnected ]
- url: https://github.com/tsailiming/openshift4-vmware-upi
  categories: [ ocp_install ]
- url: https://github.com/vchintal/ocp4-vsphere-upi-automation
  categories: [ ocp_install ]
- url: https://github.com/willb/openshift-ml-workflows-workshop
  categories: [ ocp_workloads ]
- url: https://github.com/williamcaban/ocp4-lab
  categories: [ ocp_install ]

#Repository('https://gitlab.consulting.redhat.com/nordics/ocp4-vmware-upi-prep', [Category.OCP_INSTALL])
#Repository('https://gitlab.consulting.redhat.com/jnaess/ocp4-prereqs', [Category.OCP_INSTALL])
